#!/bin/sh

. /usr/etc/rc.d/rc.funcs

if [ -z ${RC_CMD} ]; then
	cmd=$1
else
	cmd=${RC_CMD}
fi

case "$cmd" in
	start)
		rc_start
		;;
	stop)
		watchdog_stop
		rc_stop
		watchdog_start
		;;
	*)
		echo "Unrecognized option $cmd, assuming start"
		rc_start
		;;
esac
